export const GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS";
export const GET_TOKEN_FAIL = "GET_TOKEN_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";


export const FETCH_VEHICLES = 'FETCH_VEHICLES'
export const FETCH_VEHICLES_IF_NEEDED = 'FETCH_VEHICLES_IF_NEEDED'
export const FETCH_VEHICLES_PENDING = 'FETCH_VEHICLES_PENDING'
export const FETCH_VEHICLES_SUCCESS = 'FETCH_VEHICLES_SUCCESS'
export const FETCH_VEHICLES_FAILURE = 'FETCH_VEHICLES_FAILURE'

export const DELETE_VEHICLE = 'DELETE_VEHICLE'
export const DELETE_VEHICLE_PENDING = 'DELETE_VEHICLE_PENDING'
export const DELETE_VEHICLE_SUCCESS = 'DELETE_VEHICLE_SUCCESS'
export const DELETE_VEHICLE_FAILURE = 'DELETE_VEHICLE_FAILURE'

export const CREATE_VEHICLE = 'CREATE_VEHICLE'
export const CREATE_VEHICLE_PENDING = 'CREATE_VEHICLE_PENDING'
export const CREATE_VEHICLE_SUCCESS = 'CREATE_VEHICLE_SUCCESS'
export const CREATE_VEHICLE_FAILURE = 'CREATE_VEHICLE_FAILURE'

export const UPDATE_VEHICLE = 'UPDATE_VEHICLE'
export const UPDATE_VEHICLE_PENDING = 'UPDATE_VEHICLE_PENDING'
export const UPDATE_VEHICLE_SUCCESS = 'UPDATE_VEHICLE_SUCCESS'
export const UPDATE_VEHICLE_FAILURE = 'UPDATE_VEHICLE_FAILURE'